#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PaintPro.Droid.Resource", IsApplication=true)]

namespace PaintPro.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int plugins_array = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int colourPicker = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_menu_add = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_menu_archive = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_menu_edit = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_menu_preferences = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_menu_save = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_menu_show_list = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Icon = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060002
			public const int btnImageAddTab = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int btnImageDrawing = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int btnImageLoad = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int btnImageSave = 2131099656;
			
			// aapt resource value: 0x7f060006
			public const int btnImageSetting = 2131099654;
			
			// aapt resource value: 0x7f060001
			public const int imageButtonLeftMenu = 2131099649;
			
			// aapt resource value: 0x7f060009
			public const int item1 = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int item2 = 2131099658;
			
			// aapt resource value: 0x7f060000
			public const int linearLayout1 = 2131099648;
			
			// aapt resource value: 0x7f060004
			public const int relativeLayout1 = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int spPlugins = 2131099651;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int popup_menu = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int plugins_prompt = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
